title: Against anti-LGBT+ misinformation
description: 
theme: just-the-docs

url: https://opossum3.github.io/lgbt

aux_links:
  EMERGENCY EXIT: https://www.wikihow.com/Tell-the-Difference-Between-a-Frog-and-a-Toad#Considering-Behavior
